apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
  labels:
    app: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: hashicorp/http-echo
        args:
          - "-text=Go shopping"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: shop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service-node-port
spec:
  type: NodePort
  selector:
    app: shop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: shop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
    nodePort: 30085