# $LDAP/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
- name: ldappass
  files:
    - ldappass.txt

patches:
- path: configmap.yaml
  target:
    kind: ConfigMap
    name: conf
- path: deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: example