apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: shop-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: shop-storage
          mountPath: /data
      volumes:
      - name: shop-storage
        persistentVolumeClaim:
          claimName: shop-storage-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-storage-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi