apiVersion: v1
kind: Pod
metadata:
  name: shop-2-pod
  labels:
    app: shop
spec:
  hostname: shop-2
  subdomain: shop-subdomain
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "infinity"]
