apiVersion: v1
kind: Pod
metadata:
  name: shop-pod
  labels:
    app: shop
spec:
  hostname: shop
  subdomain: shop-subdomain
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "infinity"]
