apiVersion: v1
kind: Pod
metadata:
  name: video-pod
  labels:
    app: video
spec:
  hostname: video
  subdomain: video-subdomain
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "infinity"]
