# $EXT_DB/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1  # <-- Component notation
kind: Component

secretGenerator:
- name: dbpass
  files:
    - dbpass.txt

patches:
- path: configmap.yaml
  target:
    kind: ConfigMap
    name: conf
- path: deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: example